### ISSUE TITLE
Tx decode failed when calling wallet_sendToMany, Qitmeer 0.9.0

### ISSUE THREAD

**Issue by rlinxy** [Qitmeer/qitmeer-wallet#23] opened 2020-06-25 05:50 UTC
When calling the 'wallet_sendToMany', we got the error below:

Failed to sendmany: -32603: sendPostRequest: resp.Error: {"jsonrpc":"2.0","id":1,"error":{"code":-32000,"message":"Deserialization Error : Could not decode Tx: Tx.decodeWitness: non equal witness and prefix txin quantities (witness 68, prefix 101)"}}

Seems the wallet can not work with the new version 0.9.0 of Qitmeer.

Please update the code. Thx

**Comment by blocklee** [comment] 2020-06-26 16:00
The problem has been fixed, the test is available, will merge as soon as possible, please pay attention to the code update.

**Comment by dindinw** [comment] 2020-06-28 02:08
@rlinxy `wallet_sendToMany` command does not (EVER) exist under THIS codebase. Please let me know which version you are using. 
@blocklee let me know how the issue HAS been fixed?

**Comment by dindinw** [comment] 2020-06-28 03:03
@rlinxy the compatible issue for 0.9.0 network has been fixed by the commit https://github.com/Qitmeer/qitmeer-wallet/commit/cff31ef6f376dfb22ba9a18b21f7a3dd2febe8bc. Your command 'wallet_sendToMany' yet not be supported by THIS `qitmeer-wallet`

**Comment by rlinxy** [comment] 2020-06-28 04:17
@dindinw The previous wallet dev provided his personal repo
https://github.com/luoshan654/qitmeer-wallet
Our pool has been using this wallet_sendToMany API for batch payment for the last several months.

**Comment by rlinxy** [comment] 2020-06-28 04:24
We successfully made several payments yesterday after the hard fork. But we are currently stuck here:

`sendPostRequest: resp.Error: {"jsonrpc":"2.0","id":1,"error":{"code":-32000,"message":"Rule Error : Rejected transaction be443f78ecac8af02f32a7d9fcacbaf23e1685d0b5c74610bc128824fc637cc0: orphan transaction be443f78ecac8af02f32a7d9fcacbaf23e1685d0b5c74610bc128824fc637cc0 references outputs of unknown or fully-spent transaction 430a52492f88500e1df524c1bc56911eca98a172d5f1eb2ffc118a15759b72e8"}}
`

Seems the wallet keep using this UTXO everytime we start the payment, and throw this error.

I also tried just use the wallet qc sendToAddress command, got similar error as below:

sendToAddress: error -32603: sendPostRequest: resp.Error: {"jsonrpc":"2.0","id":1,"error":{"code":-32000,"message":"Rule Error : Rejected transaction 0a98b54ae882263581f1e747cd6a10dc1edbeeeec468af341cdfab191df534ea: orphan transaction 0a98b54ae882263581f1e747cd6a10dc1edbeeeec468af341cdfab191df534ea references outputs of unknown or fully-spent transaction 430a52492f88500e1df524c1bc56911eca98a172d5f1eb2ffc118a15759b72e8"}}

**Comment by dindinw** [comment] 2020-06-28 09:11
@rlinxy the issue is caused by a bug in the 0.9.0 tx RPC API which results in a wrong hash value for some`coinbase` transactions, and it has been fixed by https://github.com/Qitmeer/qitmeer/commit/44d52b892c641e47d4034d1153c32774fe0e8fda . Please use the `qitmeer` [master](https://github.com/Qitmeer/qitmeer) code (0.9.1-dev), We will issue a 0.9.1 release soon.

**Comment by dindinw** [comment] 2020-06-28 09:32
@rlinxy #22 has been merged. I think you can try 'SendToMany' now. Please make sure to use the latest trunk version 0.9.1 of `qitmeer` when you doing your test.

**Comment by dindinw** [comment] 2020-06-29 08:34
@rlinxy the issue is fixed & closed. Please reopen it if any further problems.

**Closed as completed by dindinw** 2020-06-29 08:34 UTC
